services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-reddit-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx512m"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spring_reddit_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: ${JWT_SECRET}
      SPRING_CONFIG_NAME: application
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      FILTER_API_URL: http://image-edit-service:5000/api/filter
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      image-edit-service:
        condition: service_started

  image-edit-service:
    build:
      context: ./imageProcessor
      dockerfile: Dockerfile
    container_name: spring-reddit-edit-service
    restart: unless-stopped
    ports:
      - "5000:5000"

  db:
    image: postgres:15-alpine
    container_name: spring-reddit-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: spring_reddit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d spring_reddit_db"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: