spring.application.name=spring-reddit

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-holy-wildflower-asaltfim-pooler.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASS:npg_hdbHLM4g5DKJ}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

spring.docker.compose.enabled=false
